apiVersion: v1
entries:
  sample-app:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-07-02T13:48:13.585216+02:00"
    description: A simple Python Flask app
    digest: baba21c15026418d98eb207fe2277fffcb6ebaa0279095f3526bfbd8a4192a19
    name: sample-app
    type: application
    urls:
    - https://cloudtriquetra.github.io/sample-app-helm-charts/charts/sample-app-0.1.4.tgz
    version: 0.1.4
generated: "2025-07-02T13:48:13.584273+02:00"
