apiVersion: v1
entries:
  sample-app:
  - apiVersion: v2
    appVersion: "1.1"
    created: "2025-07-02T14:09:20.23577+02:00"
    description: A simple Python Flask app
    digest: 31b8b9ba76b55632d20f165bfefe9735631e2f12fda9bd0c55aae1059e1f9201
    name: sample-app
    type: application
    urls:
    - https://cloudtriquetra.github.io/sample-app-helm-charts/charts/sample-app-0.1.5.tgz
    version: 0.1.5
generated: "2025-07-02T14:09:20.234318+02:00"
